# -*- coding: utf-8 -*-

"""
    credofasterpartnerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Denomination(object):

    """Implementation of the 'Denomination' model.

    Currency Declarative Type

    Attributes:
        name (string): Available Name: KE
        value (int): Amount to Request

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name":'name',
        "value":'value'
    }

    def __init__(self,
                 name='KE',
                 value=10):
        """Constructor for the Denomination class"""

        # Initialize members of the class
        self.name = name
        self.value = value


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get("name") if dictionary.get("name") else 'KE'
        value = dictionary.get("value") if dictionary.get("value") else 10

        # Return an object of this model
        return cls(name,
                   value)


