# -*- coding: utf-8 -*-

"""
    credofasterpartnerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class EventCallbackFeedback(object):

    """Implementation of the 'EventCallbackFeedback' model.

    TODO: type model description here.

    Attributes:
        error_code (int): TODO: type description here.
        error_description (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "error_code":'ErrorCode',
        "error_description":'ErrorDescription'
    }

    def __init__(self,
                 error_code=None,
                 error_description=None):
        """Constructor for the EventCallbackFeedback class"""

        # Initialize members of the class
        self.error_code = error_code
        self.error_description = error_description


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        error_code = dictionary.get('ErrorCode')
        error_description = dictionary.get('ErrorDescription')

        # Return an object of this model
        return cls(error_code,
                   error_description)


