# -*- coding: utf-8 -*-

"""
    credofasterpartnerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class Initiator(object):

    """Implementation of the 'Initiator' model.

    TODO: type model description here.

    Attributes:
        mtype (string): Client Type Initiating the Request
        id (string): Client ID Initiating the Request

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype":'type',
        "id":'id'
    }

    def __init__(self,
                 mtype='PARTNER',
                 id='10001'):
        """Constructor for the Initiator class"""

        # Initialize members of the class
        self.mtype = mtype
        self.id = id


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype = dictionary.get("type") if dictionary.get("type") else 'PARTNER'
        id = dictionary.get("id") if dictionary.get("id") else '10001'

        # Return an object of this model
        return cls(mtype,
                   id)


