# -*- coding: utf-8 -*-

"""
    credofasterpartnerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class PartnerAirtimeBalanceResponse(object):

    """Implementation of the 'PartnerAirtimeBalanceResponse' model.

    Balance Response

    Attributes:
        error_code (int): Code for the Request API Generated. 0: Success, Any
            other Error Code, refer to ErrorCodes Page
        error_description (string): Text Description
        unit_balance (long|int): Remaining Tentative Balance
        limit (long|int): Limit of Units to Use.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "error_code":'ErrorCode',
        "error_description":'ErrorDescription',
        "unit_balance":'UnitBalance',
        "limit":'Limit'
    }

    def __init__(self,
                 error_code=0,
                 error_description='Success.',
                 unit_balance=0,
                 limit=0):
        """Constructor for the PartnerAirtimeBalanceResponse class"""

        # Initialize members of the class
        self.error_code = error_code
        self.error_description = error_description
        self.unit_balance = unit_balance
        self.limit = limit


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        error_code = dictionary.get("ErrorCode") if dictionary.get("ErrorCode") else 0
        error_description = dictionary.get("ErrorDescription") if dictionary.get("ErrorDescription") else 'Success.'
        unit_balance = dictionary.get("UnitBalance") if dictionary.get("UnitBalance") else 0
        limit = dictionary.get("Limit") if dictionary.get("Limit") else 0

        # Return an object of this model
        return cls(error_code,
                   error_description,
                   unit_balance,
                   limit)


