# -*- coding: utf-8 -*-

"""
    credofasterpartnerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class RegisterCallbackResponse(object):

    """Implementation of the 'RegisterCallbackResponse' model.

    TODO: type model description here.

    Attributes:
        error_code (int): TODO: type description here.
        error_description (string): TODO: type description here.
        registered_callback_url (string): TODO: type description here.
        request_id (uuid|string): Tracking RequestId

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "error_code":'ErrorCode',
        "error_description":'ErrorDescription',
        "registered_callback_url":'RegisteredCallbackUrl',
        "request_id":'RequestId'
    }

    def __init__(self,
                 error_code=None,
                 error_description=None,
                 registered_callback_url=None,
                 request_id=None):
        """Constructor for the RegisterCallbackResponse class"""

        # Initialize members of the class
        self.error_code = error_code
        self.error_description = error_description
        self.registered_callback_url = registered_callback_url
        self.request_id = request_id


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        error_code = dictionary.get('ErrorCode')
        error_description = dictionary.get('ErrorDescription')
        registered_callback_url = dictionary.get('RegisteredCallbackUrl')
        request_id = dictionary.get('RequestId')

        # Return an object of this model
        return cls(error_code,
                   error_description,
                   registered_callback_url,
                   request_id)


