# -*- coding: utf-8 -*-

"""
    credofasterpartnerapi

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from credofasterpartnerapi.api_helper import APIHelper


class Configuration(object):

    """A class used for configuring the SDK by a user.

    This class need not be instantiated and all properties and methods
    are accessible without instance creation.

    """

    # Set the array parameter serialization method
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    array_serialization = "indexed"

    # An enum for SDK environments
    class Environment(object):
        # Live Environment
        PRODUCTION = 0
        # For Test Purpose
        SANDBOX = 1
        # Development
        DEVELOPMENT = 2

    # An enum for API servers
    class Server(object):
        DEFAULT = 0
        MY_CALLBACK_ENDPOINT = 1

    # The environment in which the SDK is running
    environment = Environment.SANDBOX

    # Assigned APIKey
    api_key = 'XXXX-XXXX-XXXX-XXXX'

    # Assigned ClientId
    client_id = 'ABCDEDFG1234'


    # All the environments the SDK can run in
    environments = {
        Environment.PRODUCTION: {
            Server.DEFAULT: 'https://api.partner.credofaster.co.ke',
            Server.MY_CALLBACK_ENDPOINT: 'https://posthere.io/dfd0-4d32-8ad9',
        },
        Environment.SANDBOX: {
            Server.DEFAULT: 'https://api-test.partner.credofaster.co.ke',
            Server.MY_CALLBACK_ENDPOINT: 'https://posthere.io/dfd0-4d32-8ad9',
        },
        Environment.DEVELOPMENT: {
            Server.DEFAULT: 'https://partner.credofaster.co.ke/crm_api/api/',
            Server.MY_CALLBACK_ENDPOINT: 'https://partner.credofaster.co.ke/crm_api/api/',
        },
    }

    @classmethod
    def get_base_uri(cls, server=Server.DEFAULT):
        """Generates the appropriate base URI for the environment and the server.

        Args:
            server (Configuration.Server): The server enum for which the base URI is required.

        Returns:
            String: The base URI.

        """
        return cls.environments[cls.environment][server]
